# Generated by Django 4.2 on 2023-05-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
